### ISSUE TITLE
Document CLI

### ISSUE THREAD

**Issue by tomek-he-him** [johan/format-json#1]
Hi, thanks for this great library. Keeps sanity for JSON files :)

I see you provide a CLI as well as a programmatic API, but I can't find docs for it anywhere. Also running `format-json -h` or `--help` is of no help. Have I missed something?

**Comment by johan** [comment]
It omits a proper arg processor to keep dependencies minimal, and is both very simplistic and awkward:

```
  format-json [format <terse|plain|space|lines|diffy>] path/to/file.json
  format-json < path/to/file.json
  some_pipe_chain | format-json
```

Only the file-processing variant takes an optional formatter; otherwise it produces diffy output all the time.

**Comment by tomek-he-him** [comment]
Sorry, I somehow missed your comment back then. Thanks, that makes sense – I only was after the diffy format anyway :)

**Comment by tomek-he-him** [comment]
I've submitted a PR with docs for the CLI – mostly taken from your comment. Thumbs up for the good work :)

**Comment by olsonpm** [comment]
This is incorrect.  The source for the CLI provides no format option.  As seen on [this line](https://github.com/johan/format-json/blob/master/format-json.js#L13), it only provides diffy support.

**Comment by johan** [comment]
@olsonpm Ah, quite correct! I guess that was a hack I was tinkering with locally that felt too weak to save. Pull requests making something better or removing the superfluous docs welcome. :-)
