### ISSUE TITLE
Keep empty lines?

### ISSUE THREAD

**Issue by tomek-he-him** [johan/format-json#3]
JSON is lame enough that it doesn't support comments. The only thing that makes for a bit better readability are empty lines. So I often group properties in my configuration files – like this:

``` json
{ "name": "..."
, "version": "..."

, "devDependencies":
  { "cli": "..."
  , "dependencies": "..."

  , "build": "..."
  , "dependencies": "..."
  }
}
```

_format-json_ swallows these empty lines. Is it possible/reasonable to keep them?

**Comment by johan** [comment]
I'd love a cli json formatter doing this too, but it's sadly hard to do without replacing `JSON.parse` with a full-blown low-level tokenizer/parser that recognizes the context of all newline tuples, and as such a bit beyond the scope of this package.

I'd probably accept a pull request from someone solving the problem, if there's some ingenious way of doing it that I can't think of, though. If you want a slightly less sucky JSON family format that does have comments and doesn't have the immense feature riches of yaml, I can recommend [`cson`](https://github.com/groupon/cson-parser), and the [`cson-cli`](https://github.com/johan/cson-cli) (its equivalent of `format-json`, converting/formatting in both directions to/from json).

**Comment by tomek-he-him** [comment]
Thanks for the response. Now that I think of it, it's not something I need that badly. After all, any JSON I write by hand is in diffy-formatted anyway, and contains grouping empty lines. I only really use `format-json` for automatically-generated JSON and data – and of course they don't contain any empty lines.
